server:
  port: 8090
  servlet:
    context-path: /token.svc/api/v1

app:
  log-path: ${user.home}\digicommerce\logs\token-service
spring:
  datasource:
    url: jdbc:h2:mem:tokendb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 300000
      max-lifetime: 600000 
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true